image: gitpod/workspace-python-3.11

tasks:
  - init: |
      pip install -r requirements.txt
      echo "✅ تمام کتابخانه‌ها نصب شدند"
    command: python app.py

ports:
  - port: 5000
  - port: 8080
    visibility: public
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
